### PR TITLE
README.rst - fix case for environment setup

### PR DESCRIPTION
**Pull request by kieranjol**
Barely worth a PR but figured I'd do it anyhow as I'm looking into seeing how far i get with using your tool in Ubuntu 20.04

### CODE REVIEW

**Comment by kieranjol** [comment]
Adding the codecov instatllation as well so that the tests run.
Looks like my asdco-lib setup is a bit broken:

```
$ nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=clairmeta
....................F.F.Error : Filename difference, MiniDsm_1K__Logo but expected MiniDsm_1K_Logo
........FF..FFF..F..........FFF......F................................................EEE.EEEE..................
======================================================================
ERROR: test_atmos (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 47, in test_atmos
    metadata = probe_mxf(self.get_path('atmos.mxf'))
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_audio_iop (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 39, in test_audio_iop
    metadata = probe_mxf(self.get_path('audio_iop.mxf'))
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_audio_smpte (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 43, in test_audio_smpte
    metadata = probe_mxf(self.get_path('audio_smpte.mxf'))
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_subtitle_smpte (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 51, in test_subtitle_smpte
    metadata = probe_mxf(self.get_path('subtitle_smpte.mxf'))
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_video_bitrate (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 32, in test_video_bitrate
    metadata = probe_mxf(
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_video_iop (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 20, in test_video_iop
    metadata = probe_mxf(
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
ERROR: test_video_smpte (tests.test_mxf_probe.TestAssetProbe)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_mxf_probe.py", line 26, in test_video_smpte
    metadata = probe_mxf(
  File "/home/kieranjol/ClairMeta/clairmeta/utils/probe.py", line 108, in probe_mxf
    raise ValueError(err)
ValueError: b'asdcp-info: error while loading shared libraries: libasdcp-2.10.38.so: cannot open shared object file: No such file or directory\n'

======================================================================
FAIL: test_dcp_check_bad (tests.test_cli.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_cli.py", line 81, in test_dcp_check_bad
    self.assertFalse(status)
AssertionError: True is not false

======================================================================
FAIL: test_dcp_probe_formating_json (tests.test_cli.CliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_cli.py", line 67, in test_dcp_probe_formating_json
    self.assertEqual(
AssertionError: '{\n [10950 chars]nt": "Unknown",\n                    "ChannelF[51194 chars]]\n}' != '{\n [10950 chars]nt": 12,\n                    "ChannelFormat":[76062 chars]]\n}'

======================================================================
FAIL: test_iop_vf (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 69, in test_iop_vf
    self.assertFalse(self.has_failed(DCPCheckTest.vf_missing))
AssertionError: True is not false

======================================================================
FAIL: test_mpeg (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 135, in test_mpeg
    self.assertFalse(self.check(40))
AssertionError: True is not false

======================================================================
FAIL: test_noncoherent_jp2k (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 130, in test_noncoherent_jp2k
    self.assertFalse(self.check(39))
AssertionError: True is not false

======================================================================
FAIL: test_nondci_resolution (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 106, in test_nondci_resolution
    self.assertTrue(self.has_failed('check_picture_cpl_resolution'))
AssertionError: False is not true

======================================================================
FAIL: test_over_bitrate (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 95, in test_over_bitrate
    self.assertFalse(self.has_succeeded())
AssertionError: True is not false

======================================================================
FAIL: test_smpte_vf (tests.test_dcp_check.DCPCheckTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_check.py", line 79, in test_smpte_vf
    self.assertTrue(self.check(8))
AssertionError: False is not true

======================================================================
FAIL: test_dcp_26 (tests.test_dcp_parse.DCPParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_parse.py", line 126, in test_dcp_26
    self.assertEqual(cpl['Resolution'], '1920x1080')
AssertionError: 'Unknown' != '1920x1080'
- Unknown
+ 1920x1080


======================================================================
FAIL: test_dcp_27 (tests.test_dcp_parse.DCPParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_parse.py", line 134, in test_dcp_27
    self.assertEqual(cpl['Resolution'], '3840x2160')
AssertionError: 'Unknown' != '3840x2160'
- Unknown
+ 3840x2160


======================================================================
FAIL: test_dcp_28 (tests.test_dcp_parse.DCPParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_parse.py", line 142, in test_dcp_28
    self.assertEqual(cpl['Resolution'], '4096x2160')
AssertionError: 'Unknown' != '4096x2160'
- Unknown
+ 4096x2160


======================================================================
FAIL: test_dcp_39 (tests.test_dcp_parse.DCPParseTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kieranjol/ClairMeta/tests/test_dcp_parse.py", line 195, in test_dcp_39
    self.assertEqual(cpl['DecompositionLevels'], 'Mixed')
AssertionError: 'Unknown' != 'Mixed'
- Unknown
+ Mixed


Name                                Stmts   Miss  Cover
-------------------------------------------------------
clairmeta/__init__.py                  14      1    93%
clairmeta/cli.py                       85     12    86%
clairmeta/dcp.py                      173     17    90%
clairmeta/dcp_check.py                120     29    76%
clairmeta/dcp_check_am.py              67     11    84%
clairmeta/dcp_check_atmos.py           41     27    34%
clairmeta/dcp_check_base.py            99      0   100%
clairmeta/dcp_check_cpl.py            189     39    79%
clairmeta/dcp_check_isdcf_dcnc.py     127     26    80%
clairmeta/dcp_check_picture.py        107     52    51%
clairmeta/dcp_check_pkl.py             52      7    87%
clairmeta/dcp_check_sign.py           289     52    82%
clairmeta/dcp_check_sound.py           50     33    34%
clairmeta/dcp_check_subtitle.py       340     58    83%
clairmeta/dcp_check_utils.py           36      7    81%
clairmeta/dcp_check_vol.py             19      1    95%
clairmeta/dcp_parse.py                175     18    90%
clairmeta/dcp_utils.py                105     18    83%
clairmeta/info.py                       3      0   100%
clairmeta/logger.py                    42     13    69%
clairmeta/profile.py                   29      6    79%
clairmeta/sequence.py                  33      2    94%
clairmeta/sequence_check.py            46      5    89%
clairmeta/settings.py                   6      0   100%
clairmeta/utils/__init__.py             0      0   100%
clairmeta/utils/crypto.py              11      5    55%
clairmeta/utils/file.py                77     14    82%
clairmeta/utils/isdcf.py               65      3    95%
clairmeta/utils/probe.py              160     67    58%
clairmeta/utils/sys.py                 74      0   100%
clairmeta/utils/time.py                30      0   100%
clairmeta/utils/uuid.py                10      0   100%
clairmeta/utils/xml.py                 98      6    94%
-------------------------------------------------------
TOTAL                                2772    529    81%
----------------------------------------------------------------------
Ran 136 tests in 6.264s
```

**Comment by remia** [comment]
Thanks for investigating @kieranjol 

I made a sample Dockerfile that seems to build and run all the tests successfully if you want to look at, it could help you solve your asdcplib issues maybe: https://gist.github.com/remia/3fd2948339098c5fb8fe11b1af49bdd1

For the pip install `codecov` I would argue that if you use the `pipenv install --dev` it will already install `coverage` that seems to be an equivalent.

**Comment by kieranjol** [comment]
Wow - this is great! I didn't use docker but i just ran the commands and
all tests are perfect! I'm happy to close this cos i don't want to go
through the process of reversing the last commit. So happy to see your
docker file.

**Comment by kieranjol** [comment]
p.s the reason why mine was failing originally was that I wasn't using
cmake..

**Comment by remia** [comment]
Glad to hear that, feel free to close if you are good.

The CI build seems to indicate an issue with `pipenv check` once again that we will need to look at btw.

**Pull request closed without merging**
