### PR TITLE
Add checks for some of the D-Cinema specific XML file constraints

### PR DESCRIPTION
**Pull request by matmat**
Maybe dcp_check_utils.py is not the best place for these checks, but I could not find a more suitable file.

### CODE REVIEW

**Comment by remia** [comment]
Thanks @matmat, I wasn't even aware of that standard, so I'll not be able to check that fully until I get the chance to check it.

So far I tested on ClairMeta own DCP test set and it appear to be failing because of invalid file ending ("XML file has invalid ending"), eg. on the first one ECL01-SINGLE-CPL_TST_S_EN-XX_UK-U_71_2K_DI_20171218_ECL_IOP_OV but probably most of them. That is probably the reason why Travis CI failed.

Do you know why that could be the case ?

From memory, these comes straight from Clipster.

**Comment by matmat** [comment]
Well, I think it is a bug in Clipster then :) See e.g. the discussion here: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Probably this goes undetected because equipment/software in the field are forgiving about file line endings.. Propably these tests should be separated to have the ability to skip this one.

This raises another question about how granular tests should be and how they should be grouped? Here I just throw all the tests from ST 429-17:2017 in the same function because otherwise (with separate functions) we will have to re-open and close the file several times.

On the other hand it does not feel right to bundle these checks like this.

What is your take on this?

**Comment by remia** [comment]
Yes, or maybe there were made from Windows, not sure.

I think there is an underlying design issue that facilitate / force us to write these kind of über check methods, whereas the original intent was to focus on focused atomic checks. That's kind of the reason why some check module have "assets" variants of the check method that are automatically called on each assets to avoid writing the same loop multiple times. I'm not really happy about this and don't think it's something really extensible. We need to come up with a better way.

In the mean time, yes, we need to find a way of splitting these because I can easily image lot of people getting crazy about this new line thing ;) Note that currently this check is living inside check_xml itself called from cpl / pkl / am dedicated checks, so it's already bundled with lot of other stuff like XSD validation, ...

**Comment by remia** [comment]
Sorry for the long silence, it seems that with the new proposed error accumulation scheme, that was just merged, we can go forward and implement the checks.

[Example](https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check_utils.py#L20) on how to use the `checker.error()` / `checker.fatal_error()` methods. The [name](https://github.com/Ymagis/ClairMeta/blob/develop/clairmeta/dcp_check_base.py#L148)  argument can be used to specifically reference sub errors from within the profile dictionary.

I can help if necessary, just let me know.

**Comment by matmat** [comment]
Nice! I want to look into using the new error scheme. Unfortunately I am extremly busy with other obligations at the present. I will not be able to look at this, at the earliest, in a few weeks. :-/

In the meantime, feel free to merge and/or modify this and/or my other PRs as you see fit.

**Comment by remia** [comment]
No worry @matmat !

I'll see depending on when and what we want to push for the next version.

**Comment by remia** [comment]
Thanks for the contribution again @matmat!

I'll merge and adjust the code to use the new sub-level error reporting scheme.

**Pull request merged**
